services:
  indexer:
    image: ollama-obsidian-indexer:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
# or expose on all interfaces
#      - "0.0.0.0:5000:5000"
    volumes:
# persistent storage for the indexer
#      - ./indexer:/app/storage
# volume for the note vault to use
      - /path/to/your/vault:/app/notes
    env_file:
      - .env
# optional: set environment variables directly
#    environment:
#      - OLLAMA_BASE_URL=http://localhost:11434
